#!/bin/bash
# SPDX-License-Identifier: MIT
export SCRIPTPATH=$(dirname $0)
# realpath only works with the current working directory
pushd ${SCRIPTPATH} > /dev/null
export PYTHONSCRIPTPATH=$(realpath ../lib/nilrt-snac)
popd > /dev/null
PYTHONPATH=${PYTHONPATH}:${PYTHONSCRIPTPATH} python3 -m nilrt_snac $@
