#!/bin/bash
# SPDX-License-Identifier: MIT
export SCRIPTPATH=$(dirname $0)
# realpath only works with the current working directory
pushd ${SCRIPTPATH} > /dev/null
export PYTHONSCRIPTPATH=$(realpath ../lib/nilrt-snac)
popd > /dev/null

PYTHONPATH=${PYTHONSCRIPTPATH}:${PYTHONPATH} python3 -P -B -m nilrt_snac $@
